language: node_js
node_js:
  - 8
sudo: required
install:
  - npm install -g firebase-tools
  - npm install
script:
  - npm run test
after_success:
  - npm run build
  - npm run docs
  - firebase deploy --non-interactive --token $FIREBASE_TOKEN
deploy:
  - provider: npm
    email: $EMAIL_ADDRESS
    api_key: $NPM_API
    skip_cleanup: true
    on:
      tags: true